---
title: "Blitz Talks Abstracts Symposium 2024" 
author: "UWPA" 
date: "Monday September 16th, 2024" 
output: word_document
---

## Blitz Talk #1
**Title:** Agricultural management practices associated with greater soil health indicators: evidence from long-term cropping system trials\
**Authors:** Tatiane Severo Silva, Lindsay Chamberlain Malone, Matthew D. Ruark, Chad D. Lee, David Jordan, Hanna J. Poffenbarger, Herman J. Kandel, Jeremy Ross, John M. Gaska, Joseph G. Lauer, Laura E. Lindsey, Maninder Pal Singh, Mark A. Licht, Michael Plumblee, Rachel A. Vann, Rodrigo Werle, Spyridon Mourtzinis, Seth L. Naeve, Trenton L. Roberts, Shawn P. Conley\
**Presenter:** Tatiane Severo Silva; Plant and Agroecosystem Sciences\
**Abstract:** Soil health is generally measured using physical, chemical, and biological indicators. Efforts to measure the effects of agricultural management practices on soil health remain a challenge. More studies covering a wide range of soil types and climatic conditions are needed to assist farmers in making management decisions on production practices related to soil health. In this study, we collected soil samples (0-15 cm) from 21 long-term soybean [Glycine max (L.) Merr.]-based cropping systems trials across the United States (US) to assess the impact of management practices on soil health indicators. Soil health indicators included wet aggregate stability (WAS), permanganate oxidizable carbon (POXC), organic matter loss on ignition (OM-LOI), mineralizable carbon (Min-C), water extractable organic carbon (WEOC), total organic carbon (TOC), soil extractable protein (ACE-N), total nitrogen (TN), pH, soil test phosphorus (STP), and soil test potassium (STK). Our objectives were: (i) to assess the effects of crop rotation, tillage, cover cropping, and artificial drainage on soil health indicators, (ii) to develop and share a unique and open soil health dataset with the research community for future global meta-studies, and (iii) to inform soybean farmers about the management practices that are associated with improvements on soil health. To assess the effects of management practices on soil health indicators, both meta-analysis approach and linear mixed-effect models were used. Two-crop rotations were associated with greater STP values compared to a single-crop. The inclusion of cover crops was associated with greater Min-C and WEOC compared to no cover crops. No-tillage was linked to more acidic pH compared to conventional tillage. There were no differences in observed soil tests between tile-drained and undrained treatments. Overall results suggest that cover crops can play an important role in building soil health in soybean-based cropping systems. Our open-access dataset provides a valuable resource for future research and meta-studies, ultimately contributing to the development of more effective management strategies for promoting more sustainable soybean cropping systems.\

\newpage

## Blitz Talk #2
**Title:** Environmental and biological drivers of antimicrobial resistance in wild populations\
**Authors:** Chloe A. Fouilloux, Eric Neeno-Eckwall, John Berini III, Heather Alexander, Grace Vaziri, Emma Choi, Daniel Bolnick, Amanda Hund, Jessica L. Hite\
**Presenter:** Chloe Fouilloux; Department of Pathobiology\
**Abstract:** Antimicrobial resistance (AMR) is a global health challenge that threatens the foundation of modern medicine. Globally, the agricultural sector accounts for over half of administered antibiotics. In aquatic systems, where there is no division between farmed and wild space, the spillover of pollutants from commercial fisheries increasingly challenges ecosystem health, although the consequences of these patterns remain poorly understood. Here, we combine functional genomics and modeling techniques to investigate the impact of AMR on wild fish populations of the three-spined stickleback (Gasterosteus aculeatus) across Vancouver Island. Home to one of the highest concentrations of salmon farms in Canada, Vancouver Island presents a gradient of lakes varying in connectivity to marine farming sites. This ecology allows us to establish potential links between antibiotic-use in managed areas and AMR accumulation in wild fauna. With multiple ecotypes and flexible habitat use, sticklebacks are an ideal animal model to assess AMR accumulation in diverse scenarios. Using next-generation sequencing we first screened the diversity of AMR genes in microbiomes across populations. Then, we quantified co-occurence of the most abundant mutations using ddPCR. Using structural equation modeling, we examined the relative contributions of connectivity to salmon farms, limnological, and land-use metrics on the abundance and diversity of AMR genes. Together, these data move beyond system-specific case studies and provide generalizable knowledge that can be applied to improve fisheries management.\

\newpage

## Blitz Talk #3
**Title:** The Geometric Scale Dependence of Specific Energy Absorption in Ballistic Impact Testing\
**Authors:** B. Yasara Dharmadasa, Nicholas Jaegersberg, Jizhe Cai, Ramathasan Thevamaran\
**Presenter:** Yasara Dharmadasa; Mechanical Engineering\
**Abstract:** Battlefield to space travel requires superior protective shields to ensure protection against high-velocity projectile impacts, such as bullets or micrometeorites, which can cause significant damage to personnel or components. These shields must be designed to maximize energy absorption while being lightweight. The energy absorption of the protective shield depends on many factors, such as the material rheology, layer thickness, projectile shape, and projectile velocity. Laser-induced projectile impact testing (LIPIT) is a novel ballistic impact testing setup where submicron-thick materials are impacted with microparticles in a controlled laboratory setting. Prior studies on novel emerging materials tested with LIPIT reported exceptionally high specific energy absorption compared to the bulk materials tested at the macro-scale. The current working theory is that nanofabricated protective layers significantly improve material properties and, in turn, provide superior energy absorption.  However, a key underlying assumption is that the specific energy absorption is independent of the geometric scale. To address this issue, we conducted a series of LIPIT experiments at three scales (D=4,9,20 µm) and three geometries (D/t = 4,7,17), with 20-30 impact tests performed with impact velocities varying between 200 – 800 m/s. Our results reveal a geometric scale dependency where smaller scales report a higher specific energy absorption. We further demonstrate that this scale dependency is captured by the variation of ballistic limit velocity at different scales. By scaling the specific energy absorption with the ballistic limit velocity, we reveal the existence of a scale-independent master curve that can compare the material performance across scales. Our results demonstrate that the scale dependency of specific energy absorption is different for each material system; thus, the scale of the application is a crucial factor for developing superior material systems. These findings provide fundamental knowledge critical for designing superior protective shields.\

\newpage

## Blitz Talk #4
**Title:** Exploring the Impact of Cannabis Use Patterns on Anxiety in Cancer Survivors\
**Authors:** Apoorva Reddy, PhD | John Hampton, MS | Natalie Schmitz, PharmD PhD | Betty Chewning, PhD | Amy Trentham-Dietz, PhD\
**Presenter:** Apoorva Reddy; Surgery\
**Abstract:** Background: 46% of cancer survivors in the US have anxiety. Research investigating the effects of cannabis on anxiety is in its infancy, and studies have thus far yielded mixed results. Given the therapeutic potential of the constituents of cannabis, particularly cannabidiol (CBD) and tetrahydrocannabinol (THC), we conducted a database analysis explore the association of cannabis use patterns and anxiety among cancer survivors.  Methods:  Patient-reported symptom responses were obtained from 1962 cancer survivors enrolled in the Minnesota Medical Cannabis Program (MMCP) from 2015- 2023. Multivariate linear regression is being used to evaluate the association of anxiety and cannabinoid ratio and dose of cannabis product. Regression models are adjusted for sex, age, race, ethnicity, BMI, baseline symptom score, and MMCP enrollment fee.   Results & Discussion: For every 100 mg increase in CBD, the reported anxiety score was associated with a significant reduction of 0.95 out of 10 points.  For each decrease in quintile of THC:CBD ratio, anxiety scores had a significant reduction of 0.08 out of 10 points. Additionally, taking any enteral product was significantly associated with a 30% or greater improvement in anxiety compared to not taking any enteral product.  Conclusion: In this study, lower ratios of THC to CBD and were confirmed to be most helpful for reducing anxiety in cancer survivors. This study constructs a foundation for future research to improve the tailoring of cannabis-related educational initiatives  to cancer survivors.\

\newpage

## Blitz Talk #5
**Title:** Investigating the modulation of autism spectrum disorder in a gene-by-environment model utilizing Shank3 mutant mice and polychlorinated biphenyl exposure\
**Authors:** Lindsey Felth Tanaka, Julia Tlapa, Kim Keil Stietz\
**Presenter:** Lindsey Felth Tanaka; Comparative Biosciences\
**Abstract:** Autism spectrum disorder is a neurodevelopmental disease with a multifactorial etiology that affects one in every 54 children. Genetic risk factors are thought to interact with other risk factors, resulting in a phenotype of atypical social behavior and repetitive behaviors. However, much remains to be discovered about the contribution of these individual factors to an observable phenotype or disease severity. In this gene-by-environment model, we investigate the severity of ASD in a genetic mouse model in combination with exposure to environmental toxicants.  Human gene association studies have identified Shank3, a post-synaptic scaffolding protein essential for signal transduction and plasticity in glutamatergic synapses, as a genetic risk factor for ASD.  Although homozygous Shank3 mice present with severe disease, heterozygous mice provide an intermediary phenotype that could be modulated by additional risk factors. Polychlorinated biphenyls (PCBs) are an environmental toxicant linked to neuronal development changes and implicated in the development of ASD. To investigate the interaction of PCBs with the Shank3 mutation, juvenile wild type and heterozygous Shank3 mutant mice were dosed with a mixture of PCBs for three weeks. Mice were then assessed for disease severity using the three-chamber social approach, repetitive grooming test, and olfactory habituation test. Findings in WT control mice have been replicated, and additional PCB exposure groups in the WT and shank mutants are underway. We hypothesize that if these two risk factors interact, disease severity will be higher in the Shank3 mutant with PCB exposure than in either the PCB exposure or Shank3 controls alone.\

\newpage

## Blitz Talk #6
**Title:** Using Near Infrared Light to Predict Nutrient Composition of Hazelnuts\
**Authors:** Peyton Higgins, Martha Barta, Bradley Bolling, Julie Dawson\
**Presenter:** Peyton Higgins; Plant Agroecosystem Sciences\
**Abstract:** Hazelnuts have great potential as a perennial, climate resilient crop for the Upper Midwest. American hazelnut (Corylus americana) plants are cold tolerant and disease resistant, but populations growing throughout forests in the Midwest are too variable to be grown commercially. European hazelnut (Corylus avellana) has a long history of selection for large, uniform kernels, but those plants have poor survival rates in Midwest growing conditions. Plant breeders at UW-Madison and the University of Minnesota have been collaborating to produce hybrid plants that combine the kernel quality of the European hazelnut with the hardiness of the American hazelnut. Past work has measured physical aspects of these hybrid hazelnuts, including kernel size and total yields. My work with the Midwest hazelnut plant breeding team has focused on developing efficient methods for analyzing nutrient composition of hazelnut kernels, so that we can select for good nutritional quality as we breed new hazelnut varieties. We have measured the moisture, protein, and oil content for kernels from over 120 plants so far. These measurements are prohibitively cost- and labor-intensive to run routinely, so I have also been scanning hazelnuts using near infrared (NIR) light to build a model that can predict these nutritional traits in future samples. NIR scanning takes a fraction of the time and effort of standard laboratory protocols, allowing us to rapidly measure traits for potentially hundreds of plants each year at a low cost. In the future, this NIR method could be paired with genetic information to predict which parent plants to cross to produce the best hazelnut offspring.\

\newpage

## Blitz Talk #7
**Title:** Effects of smartphone-based mindfulness training on social and emotional well-being\
**Authors:** Polina Beloborodova, Nabila Fahrin Jahan, Luka Djajakusuma, Melina Johnson, Md Touhidzamman, Mia Mohammad Imran\
**Presenter:** Polina Beloborodova; Center for Healthy Minds\
**Abstract:** This randomized controlled trial examined the effects of a 2-week digital mindfulness-based intervention (MBI) on college students’ social and emotional well-being (N = 121). Emotional well-being, including depressive feelings, anxiety, and happiness, as well as subjective social well-being, including loneliness and felt connection to others, was assessed at pre-intervention, post-intervention (middle of the semester), and follow-up (end of the semester) through short surveys that participants completed 3 times per day for 5 weeks (ecological momentary assessment; EMA). Social behavior was examined using EMA, as well as smartphone call log data and GPS location. Contrary to expectations, participants in the mindfulness group did not exhibit immediate improvements in emotional and social well-being compared to the control group. However, mindfulness training effects were observed during the end-of-semester follow-up period, indicating sustained benefits over time. Participants in the mindfulness group also were less likely to report zero social interactions than those in the control group. Exploratory analyses of mindfulness training effects on calling behavior did not reveal significant differences between the mindfulness and control groups. The analysis of location data is ongoing and will be completed by the time of the presentation. This study underscores the complexity of evaluating digital MBIs’ effects on emotional well-being and social functioning.\

\newpage

## Blitz Talk #8
**Title:** Establishing Temporal and Spatial Occupancy Trends in Wisconsin, USA, with 40 Years of Anuran Call Survey Data\
**Authors:** Zachary Gajewski, Qais Stovall, Andrew Badje, Rori Paloski. Jessica Hua\
**Presenter:** Zachary Gajewski; Forestry and wildlife ecology\
**Abstract:** Amphibians are one of the most threatened vertebrate taxa and face several threats including urbanization, disease, and climate change. Understanding how these threats alter amphibian population and communities requires an understanding of their spatial and temporal patterns. Ideally, these patterns are studied across broad spatial scales that span multiple ecoregions and include time points before and after the introduction of a threat. However, due to financial and time limitations, surveys are often limited in spatial scale and are commonly initiated only after a threat has been established. To address this gap, a relatively easy data source gaining in momentum are anuran advertisement call surveys. These surveys can be used to determine species and site occupancy and can be linked to temperature and urbanization patterns. Furthermore, these surveys can easily incorporate citizen efforts to cover broader spatial and temporal scales. In Wisconsin, USA, the Department of Natural Resources has been partnering with citizen scientists to survey twelve anuran advertisement calls across the state for 40 years. Using this dataset, we examined trends in site occupancy across the state and identified factors contributing to the occurrence of anuran species using a Bayesian occupancy model. First, we found that some species (Pseudacris crucifer and Anaxyrus americanus), had relatively stable occupancy trends throughout while species like, Lithobates sylvaticus, did not. Second, factors such as ecoregion were significant predictors of a species occupancy probability, and generally species richness decreased in higher latitudes. Third, using species cooccurrence patterns, we were able to improve estimates of species occupancy for data poor species. Lastly, we examined how urbanization decreased species richness in Madison, WI city area. Collectively, we show that citizen-collected anuran call survey data can be used to establish both spatial and temporal trends in twelve difference anuran species to inform priorities for anuran conservation efforts.\

\newpage

## Blitz Talk #9
**Title:** Riding in the Moment: An adaptive horseback riding program for persons living with dementia and their carepartners\
**Authors:** Benazir Meera, Beth Fields\
**Presenter:** Benazir Meera; Kinesiology\
**Abstract:** More than 120,000 residents in Wisconsin live with Alzheimer's disease and related dementias and may experience social isolation and loneliness, negatively affecting their health and quality of life, as well as that of their family caregivers.  To combat these negative outcomes, persons living with dementia and their families are seeking meaningful programs in supportive social and community settings.  Evidence supports the benefits of non-pharmacological interventions involving animals for persons living with dementia. The animal “acts as a bonding agent, placing persons living with dementia at ease, in a state of immediate intimacy, and positions the interventionist as less threatening,” thus creating a welcoming environment for behavior change. One such non-pharmacological intervention is Riding in the Moment — a nationwide standardized adaptive horseback riding program.  Riding in the Moment is an evidence-informed adaptive horseback riding program designed to enhance the health and quality of life of persons living with dementia and their families. Riding in the Moment is unique because it incorporates horses and other equine interactions within the natural environment, providing an enriched environmental opportunity that persons living with dementia may not experience otherwise. Over 8 weeks, participants are provided a safe, supportive, and dynamic context where they can ride, groom, and pet horses and socialize with friends, staff, and other community member volunteers. This program is led by a national community academic team consisting of dementia and caregiving advocates, academic researchers, aging and disability service experts, and equine-assisted service professionals. Preliminary findings show that Riding in the Moment enhances the quality of life of persons living with dementia and that of their caregivers and is deemed a safe, acceptable, and appropriate non-pharmacological intervention for persons living with dementia.\

\newpage

## Blitz Talk #10
**Title:** Is insulin resistance linked to reduced cerebral blood flow or cognitive function in adolescents?\
**Authors:** Kaylin D. Didier, Brett M. Wannebo, Aaron T. Ward, Shawn Bolin, Marlowe W. Eldridge, Oliver Wieben, Aaron L. Carrel, William G. Schrage\
**Presenter:** Kaylin Didier; Kinesiology\
**Abstract:** Background: Adolescents are in a key growth period that heavily influences future brain health. Approximately 1 in 5 adolescents are obese in the US, and up to half of them exhibit some form of insulin resistance (IR). Notably, insulin acts as a metabolic hormone, a neurotrophic growth factor, and a vasodilator. Reduced vasodilation may lead to reduced cerebral blood flow (CBF), and lower CBF in older adults is associated with reduced cognition and increased risk of stroke and neurologic disease. Given this background, IR may negatively impact adolescent brain health in part due to lower CBF. Therefore, we hypothesized CBF and cognitive function would decrease as the level of IR increased.    Methods: Adolescents (n=13; age 15±2 yrs) were studied. IR was estimated by calculating HOMA-IR (fasting glucose and insulin), spanning a spectrum of IR (excluding diabetes). Subjects underwent a magnetic resonance imaging (MRI) study visit to assess cerebral perfusion and performed cognitive tests with the NIH-Toolbox.     Results: CBF was decreased in some regions of the brain as HOMA-IR increased: amygdala (r2=0.33, p=0.024) and parahippocampal gyrus (r2=0.28, p=0.041). Borderline significant decreases were found for: total gray matter (r2=0.26, p=0.051), anterior cingulate cortex (r2=0.26, p=0.052), and hippocampus (r2=0.23, p=0.071) perfusion as HOMA-IR increased. However, not all regions were decreased: total white matter, precuneus, thalamus proper, and entorhinal cortex. Increasing HOMA-IR in adolescents showed a trend of decreased cognitive function: Pattern Comparison Processing Speed (r2=0.635, p=0.04), Flanker Inhibitory Control and Attention (r2=0.18, p=0.286), Picture Sequence (r2=0.47, p=0.06), and Verbal Comp (r2=0.31, p=0.074).   Conclusions:  These results suggest there is a significant reduction in CBF at key brain regions associated with memory, processing speed, and verbal comprehension in adolescents with increasing HOMA-IR. Additionally, total gray matter shows a trend of decreased CBF with increasing insulin resistance. These findings partially support our hypothesis that CBF and cognitive function are associated with increasing IR in adolescents, which may negatively impact long-term brain health.\

\newpage

## Blitz Talk #11
**Title:** ALS-linked mutation alters neuronal mitochondrial turnover at the synapse\
**Authors:** Hiu-Tung C Wong, Angelica E Lang, Chris Stein, Catherine M Drerup\
**Presenter:** Candy Wong; Integrative Biology\
**Abstract:** Mitochondrial population maintenance in neurons is essential for neuron function and survival. Contact sites between mitochondria and the endoplasmic reticulum (ER) are poised to regulate mitochondrial homeostasis in neurons. These contact sites can function to facilitate transfer of calcium and lipids between the organelles and have been shown to regulate aspects of mitochondrial fission and fusion dynamics. VapB is an ER membrane protein present at a subset of ER-mitochondria contact sites. A proline-to-serine mutation at amino acid 56 (P56S) in VapB correlates with susceptibility to amyotrophic lateral sclerosis (ALS) type 8. Given the relationship between failed mitochondrial health and neurodegenerative disease, we investigated the function of VapB in mitochondrial population maintenance. We demonstrate that transgenic expression of VapBP56S in zebrafish larvae (sex undetermined) increased mitochondrial biogenesis, causing increased mitochondrial population size in the axon terminal. Expression of wild type VapB did not alter biogenesis but, instead, increased mitophagy in the axon terminal. Using genetic manipulations to independently increase mitochondrial biogenesis in neurons, we show that biogenesis is normally balanced by mitophagy to maintain a constant mitochondrial population size. VapBP56S transgenics fail to increase mitophagy to compensate for the increase in mitochondrial biogenesis, suggesting an impaired mitophagic response. Finally, using a synthetic ER-mitochondria tether, we show that VapB’s function in mitochondrial turnover is likely independent of ER-mitochondrial tethering by contact sites. Our findings demonstrate that VapB can control mitochondrial turnover in the axon terminal, and this function is altered by the P56S ALS-linked mutation.\

\newpage

## Blitz Talk #12
**Title:** Air quality and health effects of a transition to ammonia–fueled shipping in Singapore\
**Authors:** Sagar Rathod, Morgan R Edwards, Chaitri Roy, Laura Warnecke, Peter Rafaj, Gregor Kiesewetter, and Zbigniew Klimont\
**Presenter:** Sagar Rathod; Atmospheric and Oceanic Sciences\
**Abstract:** Ammonia has been proposed to replace heavy fuel oil (HFO) in the shipping industry by 2050. When produced with low-carbon electricity, ammonia can reduce greenhouse gas emissions. However, ammonia emissions also contribute to local air pollution via the formation of secondary particulate matter. We estimate the potential ammonia emissions from storage and bunkering operations for shipping in Singapore, a port that accounts for 20% of global bunker fuel sales, and their impacts on air quality and health. Fuel storage and bunkering can increase total gaseous ammonia emissions in Singapore by up to a factor of four and contribute to a 25%–50% increase in ambient PM2.5 concentration compared to a baseline scenario with HFO, leading to an estimated 210–460 premature mortalities in Singapore (30%–70% higher than the baseline). Proper abatement on storage and bunkering can reduce these emissions and even improve ambient PM2.5 concentrations compared to the baseline. Overall, while an energy transition from HFO to ammonia in the shipping industry could reduce global greenhouse gas and air pollutant burdens, local policies will be important to avoid negative impacts on the communities living near its supply chain.\

\newpage

